# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- import_role:
    name: tosit.tdp.utils.kerberos
    tasks_from: install

- import_role:
    name: tosit.tdp.utils.kerberos
    tasks_from: create_principal_keytab
  vars:
    principal: "kafka/{{ ansible_fqdn }}"
    keytab: "kafka.service.keytab"
    user: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: "600"

- import_role:
    name: tosit.tdp.utils.kerberos
    tasks_from: create_principal_keytab
  vars:
    principal: "HTTP/{{ ansible_fqdn }}"
    keytab: "spnego.service.keytab"
    user: "root"
    group: "{{ hadoop_group }}"
    mode: "640"
