---
# SSH keygen parameters
local_ssh_key_path: "files/ssh_keys/id_rsa_{{ owner }}"
local_ssh_public_key_path: "files/id_rsa_{{ owner }}.pub"
size: 2048
type: rsa
mode: 0644
comment: tdp
owner: "{{ owner }}"
group: "{{ owner }}"
passphrase: ""

# Deploying public key
remote_ssh_public_key_path: "/home/{{ owner }}/.ssh/id_rsa.pub"
remote_authorised_keys_path: "/home/{{ owner }}/.ssh/authorized_keys"
remote_ssh_private_key_path: "/home/{{ owner }}/.ssh/id_rsa"