---
- name: Configure chrony for VM hibernation/reboot
  replace:
    dest: /etc/chrony.conf
    regexp: '^makestep.*$'
    replace: 'makestep 1 -1'
    backup: yes

- name: Restart chronyd
  service:
    name: chronyd
    state: restarted
