---
- name: Pip install flower 
  pip:
    name: "flower"
    executable: pip3
    extra_args: --constraint /tmp/constraints-3.6.txt

- name: Template Airflow worker service file
  template:
    src: airflow-worker.service.j2
    dest: /usr/lib/systemd/system/airflow-worker.service

- name: Template Airflow flower service file
  template:
    src: airflow-flower.service.j2
    dest: /usr/lib/systemd/system/airflow-flower.service