---
- name: Create rangeradmin user if not exists
  become_user: postgres
  shell: psql -tc "SELECT 1 FROM pg_user WHERE usename = 'rangeradmin'" | grep -q 1 || (echo "CREATE USER rangeradmin WITH PASSWORD 'rangeradmin';" | psql -U postgres)

- name: Create ranger database if it doesn't exist already
  become_user: postgres
  shell: psql -tc "SELECT 1 FROM pg_database WHERE datname = 'ranger'" | grep -q 1 || (echo "CREATE DATABASE ranger;" | psql -U postgres)

- name: Grant all privileges to rangeradmin user on ranger database
  become_user: postgres
  shell: echo "GRANT ALL PRIVILEGES ON DATABASE ranger TO rangeradmin;" | psql -U postgres
